### ISSUE TITLE
Building 3 different micro services within the same repo?

### ISSUE THREAD

**Issue by KingScooty** [michaelcontento/circleci-matrix#15]
I've just stumbled across this tool now, and i think it might help me with my situation, but i just want to be 100% sure before i spend any time getting it setup.

I've got a repo for a project that's broken down into 3 microservices: `api`, `worker`, `web`. Each one will have it's own docker image with different dependencies and tests. Once the tests pass, ideally, i'd like to build each docker image, and then push each one do dockerhub ready for deployment.

Is this scenario a bit too complicated for using this tool, or perfect for it?  Reason i ask, is the config examples in the readme are fairly basic, and i'm curious what can be achieved (and what can't) by using this tool.

**Comment by michaelcontento** [comment]
Sorry for the bad news, but due to time constraints I'm no longer able to maintain this tools. 😞 
But thank you for using/trying this in the first place! 🎉

**Comment by michaelcontento** [comment]
After if pushed c0fe6ab2c850e239e66e9b137bc91f148ecdc177, @jcfr and @thewtex, part of the scikit-build organization (https://github.com/scikit-build), wrote me a mail and they are here to keep circlci-matrix alive. 

I've re-opened this issue for them and please do give them a warm welcome 👏

**Comment by thewtex** [comment]
Thank you, @michaelcontento, both your work on the software and for enabling others to keep it alive and move it forward!

**Comment by michaelcontento** [comment]
@KingScooty A very late response, but you could achieve your result with a `cirlceci-matrix.yml` roughly looking like this:

```yml
env:
    - SERVICE=api
    - SERVICE=worker
    - SERVICE=web

command:
    - cd $SERVICE && docker build . -t $SERVICE:latest
```

Your `circle.yml` would look something like:

```yml
# [...]

dependencies:
    pre:
    - curl -fsSL https://git.io/v2Ifn | bash

test:
    override:
    - circleci-matrix
    post:
    - ./someScriptThatWillPushAlleImagesToYourRegistry.sh

# [...]
```
